name: Publish production
on:
  push:
    branches:
      - production
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: -- Step 1 -- Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: -- Step 2 -- Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: -- Step 3 -- Use Expo action
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-token: ${{ secrets.EXPO_TOKEN }}
      - name: -- Step 4 -- Install dependencies
        run: yarn install
      - name: -- Step 5 -- Publish
        env:
          SENTRY_ORGANIZATION: ${{ secrets.SENTRY_ORGANIZATION }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_DEPLOY_ENV: production
        run: expo publish --release-channel=${GITHUB_REF#refs/heads/}
