name: Build staging
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: -- Step 1 -- Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: -- Step 2 -- Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: -- Step 3 -- Use Expo action
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-token: ${{ secrets.EXPO_TOKEN }}
      - name: -- Step 4 -- Install node dependencies
        run: yarn install
      - name: -- Step 5 -- Install native dependencies
        run: npx pod-install
      - name: -- Step 6 -- Install ruby dependencies
        run: bundle install
      - name: -- Step 7 -- Run fastlane
        env:
          TOOOT_ENVIRONMENT: staging
          SENTRY_ORGANIZATION: ${{ secrets.SENTRY_ORGANIZATION }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}
          SUPPLY_JSON_KEY_DATA: ${{ secrets.SUPPLY_JSON_KEY_DATA }}
          FL_GITHUB_RELEASE_API_BEARER: ${{ secrets.GITHUB_TOKEN }}
        run: yarn app:build
